// Static OpenAlex subfield -> field -> domain hierarchy.
// Source: https://api.openalex.org/subfields (fetched 2026-07-23, 252 subfields).
// Used for the Rao-Stirling-style distance-weighted diversity measure (metric d),
// which needs each subfield's parent field/domain to compute near/medium/far distances.
// Columns: [subfieldId, subfieldName, fieldId, fieldName, domainId, domainName]
const OPENALEX_SUBFIELD_TABLE = [
  ["1100", "General Agricultural and Biological Sciences", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1102", "Agronomy and Crop Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1103", "Animal Science and Zoology", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1104", "Aquatic Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1105", "Ecology, Evolution, Behavior and Systematics", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1106", "Food Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1107", "Forestry", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1108", "Horticulture", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1109", "Insect Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1110", "Plant Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1111", "Soil Science", "11", "Agricultural and Biological Sciences", "1", "Life Sciences"],
  ["1200", "General Arts and Humanities", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1202", "History", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1203", "Language and Linguistics", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1204", "Archeology", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1205", "Classics", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1206", "Conservation", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1207", "History and Philosophy of Science", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1208", "Literature and Literary Theory", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1209", "Museology", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1210", "Music", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1211", "Philosophy", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1212", "Religious studies", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1213", "Visual Arts and Performing Arts", "12", "Arts and Humanities", "2", "Social Sciences"],
  ["1302", "Aging", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1303", "Biochemistry", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1304", "Biophysics", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1305", "Biotechnology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1306", "Cancer Research", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1307", "Cell Biology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1308", "Clinical Biochemistry", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1309", "Developmental Biology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1310", "Endocrinology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1311", "Genetics", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1312", "Molecular Biology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1313", "Molecular Medicine", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1314", "Physiology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1315", "Structural Biology", "13", "Biochemistry, Genetics and Molecular Biology", "1", "Life Sciences"],
  ["1402", "Accounting", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1403", "Business and International Management", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1404", "Management Information Systems", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1405", "Management of Technology and Innovation", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1406", "Marketing", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1407", "Organizational Behavior and Human Resource Management", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1408", "Strategy and Management", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1409", "Tourism, Leisure and Hospitality Management", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1410", "Industrial relations", "14", "Business, Management and Accounting", "2", "Social Sciences"],
  ["1502", "Bioengineering", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1503", "Catalysis", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1504", "Chemical Health and Safety", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1506", "Filtration and Separation", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1507", "Fluid Flow and Transfer Processes", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1508", "Process Chemistry and Technology", "15", "Chemical Engineering", "3", "Physical Sciences"],
  ["1602", "Analytical Chemistry", "16", "Chemistry", "3", "Physical Sciences"],
  ["1603", "Electrochemistry", "16", "Chemistry", "3", "Physical Sciences"],
  ["1604", "Inorganic Chemistry", "16", "Chemistry", "3", "Physical Sciences"],
  ["1605", "Organic Chemistry", "16", "Chemistry", "3", "Physical Sciences"],
  ["1606", "Physical and Theoretical Chemistry", "16", "Chemistry", "3", "Physical Sciences"],
  ["1607", "Spectroscopy", "16", "Chemistry", "3", "Physical Sciences"],
  ["1702", "Artificial Intelligence", "17", "Computer Science", "3", "Physical Sciences"],
  ["1703", "Computational Theory and Mathematics", "17", "Computer Science", "3", "Physical Sciences"],
  ["1704", "Computer Graphics and Computer-Aided Design", "17", "Computer Science", "3", "Physical Sciences"],
  ["1705", "Computer Networks and Communications", "17", "Computer Science", "3", "Physical Sciences"],
  ["1706", "Computer Science Applications", "17", "Computer Science", "3", "Physical Sciences"],
  ["1707", "Computer Vision and Pattern Recognition", "17", "Computer Science", "3", "Physical Sciences"],
  ["1708", "Hardware and Architecture", "17", "Computer Science", "3", "Physical Sciences"],
  ["1709", "Human-Computer Interaction", "17", "Computer Science", "3", "Physical Sciences"],
  ["1710", "Information Systems", "17", "Computer Science", "3", "Physical Sciences"],
  ["1711", "Signal Processing", "17", "Computer Science", "3", "Physical Sciences"],
  ["1712", "Software", "17", "Computer Science", "3", "Physical Sciences"],
  ["1800", "General Decision Sciences", "18", "Decision Sciences", "2", "Social Sciences"],
  ["1802", "Information Systems and Management", "18", "Decision Sciences", "2", "Social Sciences"],
  ["1803", "Management Science and Operations Research", "18", "Decision Sciences", "2", "Social Sciences"],
  ["1804", "Statistics, Probability and Uncertainty", "18", "Decision Sciences", "2", "Social Sciences"],
  ["1902", "Atmospheric Science", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1904", "Earth-Surface Processes", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1906", "Geochemistry and Petrology", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1907", "Geology", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1908", "Geophysics", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1910", "Oceanography", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1911", "Paleontology", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["1912", "Space and Planetary Science", "19", "Earth and Planetary Sciences", "3", "Physical Sciences"],
  ["2000", "General Economics, Econometrics and Finance", "20", "Economics, Econometrics and Finance", "2", "Social Sciences"],
  ["2002", "Economics and Econometrics", "20", "Economics, Econometrics and Finance", "2", "Social Sciences"],
  ["2003", "Finance", "20", "Economics, Econometrics and Finance", "2", "Social Sciences"],
  ["2100", "General Energy", "21", "Energy", "3", "Physical Sciences"],
  ["2102", "Energy Engineering and Power Technology", "21", "Energy", "3", "Physical Sciences"],
  ["2103", "Fuel Technology", "21", "Energy", "3", "Physical Sciences"],
  ["2104", "Nuclear Energy and Engineering", "21", "Energy", "3", "Physical Sciences"],
  ["2105", "Renewable Energy, Sustainability and the Environment", "21", "Energy", "3", "Physical Sciences"],
  ["2200", "General Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2202", "Aerospace Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2203", "Automotive Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2204", "Biomedical Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2205", "Civil and Structural Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2206", "Computational Mechanics", "22", "Engineering", "3", "Physical Sciences"],
  ["2207", "Control and Systems Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2208", "Electrical and Electronic Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2209", "Industrial and Manufacturing Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2210", "Mechanical Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2211", "Mechanics of Materials", "22", "Engineering", "3", "Physical Sciences"],
  ["2212", "Ocean Engineering", "22", "Engineering", "3", "Physical Sciences"],
  ["2213", "Safety, Risk, Reliability and Quality", "22", "Engineering", "3", "Physical Sciences"],
  ["2214", "Media Technology", "22", "Engineering", "3", "Physical Sciences"],
  ["2215", "Building and Construction", "22", "Engineering", "3", "Physical Sciences"],
  ["2216", "Architecture", "22", "Engineering", "3", "Physical Sciences"],
  ["2302", "Ecological Modeling", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2303", "Ecology", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2304", "Environmental Chemistry", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2305", "Environmental Engineering", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2306", "Global and Planetary Change", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2307", "Health, Toxicology and Mutagenesis", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2308", "Management, Monitoring, Policy and Law", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2309", "Nature and Landscape Conservation", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2310", "Pollution", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2311", "Industrial and Manufacturing Engineering", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2312", "Water Science and Technology", "23", "Environmental Science", "3", "Physical Sciences"],
  ["2402", "Applied Microbiology and Biotechnology", "24", "Immunology and Microbiology", "1", "Life Sciences"],
  ["2403", "Immunology", "24", "Immunology and Microbiology", "1", "Life Sciences"],
  ["2404", "Microbiology", "24", "Immunology and Microbiology", "1", "Life Sciences"],
  ["2405", "Parasitology", "24", "Immunology and Microbiology", "1", "Life Sciences"],
  ["2406", "Virology", "24", "Immunology and Microbiology", "1", "Life Sciences"],
  ["2500", "General Materials Science", "25", "Materials Science", "3", "Physical Sciences"],
  ["2502", "Biomaterials", "25", "Materials Science", "3", "Physical Sciences"],
  ["2503", "Ceramics and Composites", "25", "Materials Science", "3", "Physical Sciences"],
  ["2504", "Electronic, Optical and Magnetic Materials", "25", "Materials Science", "3", "Physical Sciences"],
  ["2505", "Materials Chemistry", "25", "Materials Science", "3", "Physical Sciences"],
  ["2506", "Metals and Alloys", "25", "Materials Science", "3", "Physical Sciences"],
  ["2507", "Polymers and Plastics", "25", "Materials Science", "3", "Physical Sciences"],
  ["2508", "Surfaces, Coatings and Films", "25", "Materials Science", "3", "Physical Sciences"],
  ["2602", "Algebra and Number Theory", "26", "Mathematics", "3", "Physical Sciences"],
  ["2604", "Applied Mathematics", "26", "Mathematics", "3", "Physical Sciences"],
  ["2605", "Computational Mathematics", "26", "Mathematics", "3", "Physical Sciences"],
  ["2607", "Discrete Mathematics and Combinatorics", "26", "Mathematics", "3", "Physical Sciences"],
  ["2608", "Geometry and Topology", "26", "Mathematics", "3", "Physical Sciences"],
  ["2610", "Mathematical Physics", "26", "Mathematics", "3", "Physical Sciences"],
  ["2611", "Modeling and Simulation", "26", "Mathematics", "3", "Physical Sciences"],
  ["2612", "Numerical Analysis", "26", "Mathematics", "3", "Physical Sciences"],
  ["2613", "Statistics and Probability", "26", "Mathematics", "3", "Physical Sciences"],
  ["2614", "Theoretical Computer Science", "26", "Mathematics", "3", "Physical Sciences"],
  ["2702", "Anatomy", "27", "Medicine", "4", "Health Sciences"],
  ["2703", "Anesthesiology and Pain Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2704", "Biochemistry", "27", "Medicine", "4", "Health Sciences"],
  ["2705", "Cardiology and Cardiovascular Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2706", "Critical Care and Intensive Care Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2707", "Complementary and alternative medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2708", "Dermatology", "27", "Medicine", "4", "Health Sciences"],
  ["2711", "Emergency Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2712", "Endocrinology, Diabetes and Metabolism", "27", "Medicine", "4", "Health Sciences"],
  ["2713", "Epidemiology", "27", "Medicine", "4", "Health Sciences"],
  ["2714", "Family Practice", "27", "Medicine", "4", "Health Sciences"],
  ["2715", "Gastroenterology", "27", "Medicine", "4", "Health Sciences"],
  ["2716", "Genetics", "27", "Medicine", "4", "Health Sciences"],
  ["2717", "Geriatrics and Gerontology", "27", "Medicine", "4", "Health Sciences"],
  ["2718", "Health Informatics", "27", "Medicine", "4", "Health Sciences"],
  ["2720", "Hematology", "27", "Medicine", "4", "Health Sciences"],
  ["2721", "Hepatology", "27", "Medicine", "4", "Health Sciences"],
  ["2723", "Immunology and Allergy", "27", "Medicine", "4", "Health Sciences"],
  ["2724", "Internal Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2725", "Infectious Diseases", "27", "Medicine", "4", "Health Sciences"],
  ["2726", "Microbiology", "27", "Medicine", "4", "Health Sciences"],
  ["2727", "Nephrology", "27", "Medicine", "4", "Health Sciences"],
  ["2728", "Neurology", "27", "Medicine", "4", "Health Sciences"],
  ["2729", "Obstetrics and Gynecology", "27", "Medicine", "4", "Health Sciences"],
  ["2730", "Oncology", "27", "Medicine", "4", "Health Sciences"],
  ["2731", "Ophthalmology", "27", "Medicine", "4", "Health Sciences"],
  ["2732", "Orthopedics and Sports Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2733", "Otorhinolaryngology", "27", "Medicine", "4", "Health Sciences"],
  ["2734", "Pathology and Forensic Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2735", "Pediatrics, Perinatology and Child Health", "27", "Medicine", "4", "Health Sciences"],
  ["2736", "Pharmacology", "27", "Medicine", "4", "Health Sciences"],
  ["2737", "Physiology", "27", "Medicine", "4", "Health Sciences"],
  ["2738", "Psychiatry and Mental health", "27", "Medicine", "4", "Health Sciences"],
  ["2739", "Public Health, Environmental and Occupational Health", "27", "Medicine", "4", "Health Sciences"],
  ["2740", "Pulmonary and Respiratory Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2741", "Radiology, Nuclear Medicine and Imaging", "27", "Medicine", "4", "Health Sciences"],
  ["2742", "Rehabilitation", "27", "Medicine", "4", "Health Sciences"],
  ["2743", "Reproductive Medicine", "27", "Medicine", "4", "Health Sciences"],
  ["2745", "Rheumatology", "27", "Medicine", "4", "Health Sciences"],
  ["2746", "Surgery", "27", "Medicine", "4", "Health Sciences"],
  ["2747", "Transplantation", "27", "Medicine", "4", "Health Sciences"],
  ["2748", "Urology", "27", "Medicine", "4", "Health Sciences"],
  ["2802", "Behavioral Neuroscience", "28", "Neuroscience", "1", "Life Sciences"],
  ["2803", "Biological Psychiatry", "28", "Neuroscience", "1", "Life Sciences"],
  ["2804", "Cellular and Molecular Neuroscience", "28", "Neuroscience", "1", "Life Sciences"],
  ["2805", "Cognitive Neuroscience", "28", "Neuroscience", "1", "Life Sciences"],
  ["2806", "Developmental Neuroscience", "28", "Neuroscience", "1", "Life Sciences"],
  ["2807", "Endocrine and Autonomic Systems", "28", "Neuroscience", "1", "Life Sciences"],
  ["2808", "Neurology", "28", "Neuroscience", "1", "Life Sciences"],
  ["2809", "Sensory Systems", "28", "Neuroscience", "1", "Life Sciences"],
  ["2910", "Issues, ethics and legal aspects", "29", "Nursing", "4", "Health Sciences"],
  ["2911", "Leadership and Management", "29", "Nursing", "4", "Health Sciences"],
  ["2916", "Nutrition and Dietetics", "29", "Nursing", "4", "Health Sciences"],
  ["2922", "Research and Theory", "29", "Nursing", "4", "Health Sciences"],
  ["3002", "Drug Discovery", "30", "Pharmacology, Toxicology and Pharmaceutics", "1", "Life Sciences"],
  ["3003", "Pharmaceutical Science", "30", "Pharmacology, Toxicology and Pharmaceutics", "1", "Life Sciences"],
  ["3004", "Pharmacology", "30", "Pharmacology, Toxicology and Pharmaceutics", "1", "Life Sciences"],
  ["3005", "Toxicology", "30", "Pharmacology, Toxicology and Pharmaceutics", "1", "Life Sciences"],
  ["3102", "Acoustics and Ultrasonics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3103", "Astronomy and Astrophysics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3104", "Condensed Matter Physics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3105", "Instrumentation", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3106", "Nuclear and High Energy Physics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3107", "Atomic and Molecular Physics, and Optics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3108", "Radiation", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3109", "Statistical and Nonlinear Physics", "31", "Physics and Astronomy", "3", "Physical Sciences"],
  ["3200", "General Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3202", "Applied Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3203", "Clinical Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3204", "Developmental and Educational Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3205", "Experimental and Cognitive Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3206", "Neuropsychology and Physiological Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3207", "Social Psychology", "32", "Psychology", "2", "Social Sciences"],
  ["3300", "General Social Sciences", "33", "Social Sciences", "2", "Social Sciences"],
  ["3302", "Archeology", "33", "Social Sciences", "2", "Social Sciences"],
  ["3303", "Development", "33", "Social Sciences", "2", "Social Sciences"],
  ["3304", "Education", "33", "Social Sciences", "2", "Social Sciences"],
  ["3305", "Geography, Planning and Development", "33", "Social Sciences", "2", "Social Sciences"],
  ["3306", "Health", "33", "Social Sciences", "2", "Social Sciences"],
  ["3307", "Human Factors and Ergonomics", "33", "Social Sciences", "2", "Social Sciences"],
  ["3308", "Law", "33", "Social Sciences", "2", "Social Sciences"],
  ["3309", "Library and Information Sciences", "33", "Social Sciences", "2", "Social Sciences"],
  ["3310", "Linguistics and Language", "33", "Social Sciences", "2", "Social Sciences"],
  ["3311", "Safety Research", "33", "Social Sciences", "2", "Social Sciences"],
  ["3312", "Sociology and Political Science", "33", "Social Sciences", "2", "Social Sciences"],
  ["3313", "Transportation", "33", "Social Sciences", "2", "Social Sciences"],
  ["3314", "Anthropology", "33", "Social Sciences", "2", "Social Sciences"],
  ["3315", "Communication", "33", "Social Sciences", "2", "Social Sciences"],
  ["3316", "Cultural Studies", "33", "Social Sciences", "2", "Social Sciences"],
  ["3317", "Demography", "33", "Social Sciences", "2", "Social Sciences"],
  ["3318", "Gender Studies", "33", "Social Sciences", "2", "Social Sciences"],
  ["3319", "Life-span and Life-course Studies", "33", "Social Sciences", "2", "Social Sciences"],
  ["3320", "Political Science and International Relations", "33", "Social Sciences", "2", "Social Sciences"],
  ["3321", "Public Administration", "33", "Social Sciences", "2", "Social Sciences"],
  ["3322", "Urban Studies", "33", "Social Sciences", "2", "Social Sciences"],
  ["3402", "Equine", "34", "Veterinary", "4", "Health Sciences"],
  ["3404", "Small Animals", "34", "Veterinary", "4", "Health Sciences"],
  ["3500", "General Dentistry", "35", "Dentistry", "4", "Health Sciences"],
  ["3504", "Oral Surgery", "35", "Dentistry", "4", "Health Sciences"],
  ["3505", "Orthodontics", "35", "Dentistry", "4", "Health Sciences"],
  ["3506", "Periodontics", "35", "Dentistry", "4", "Health Sciences"],
  ["3600", "General Health Professions", "36", "Health Professions", "4", "Health Sciences"],
  ["3603", "Complementary and Manual Therapy", "36", "Health Professions", "4", "Health Sciences"],
  ["3604", "Emergency Medical Services", "36", "Health Professions", "4", "Health Sciences"],
  ["3605", "Health Information Management", "36", "Health Professions", "4", "Health Sciences"],
  ["3607", "Medical Laboratory Technology", "36", "Health Professions", "4", "Health Sciences"],
  ["3608", "Medical Terminology", "36", "Health Professions", "4", "Health Sciences"],
  ["3609", "Occupational Therapy", "36", "Health Professions", "4", "Health Sciences"],
  ["3611", "Pharmacy", "36", "Health Professions", "4", "Health Sciences"],
  ["3612", "Physical Therapy, Sports Therapy and Rehabilitation", "36", "Health Professions", "4", "Health Sciences"],
  ["3614", "Radiological and Ultrasound Technology", "36", "Health Professions", "4", "Health Sciences"],
  ["3616", "Speech and Hearing", "36", "Health Professions", "4", "Health Sciences"],
];

const SUBFIELD_BY_ID = Object.fromEntries(
  OPENALEX_SUBFIELD_TABLE.map(r => [r[0], { id: r[0], name: r[1], fieldId: r[2], fieldName: r[3], domainId: r[4], domainName: r[5] }])
);
